### PR TITLE
Dev/edit code window

### PR DESCRIPTION
**Pull request by THEGOLDENPRO**
- Added a separate window for editing/modifying custom scripts for effects.

### CODE REVIEW

**Comment by mc2285** [comment]
Looks good - gonna check if it works and merge today

**Review by mc2285 — APPROVED** [review]
Works - merging

**Comment by mc2285** [comment]
@THEGOLDENPRO - there was a small fix - see d2e255b

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO - there was a small fix - see [d2e255b](https://github.com/CZEditor/CZEditor/commit/d2e255bdccb13e176f4d054205b60b9c344b4cf7)

ah okay I see, thanks

**Pull request merged**
